Create SolveMeFirst.cs
revanthakula/Hackerrank-Algorithms- pull request #1
Opened 2021-06-24 12:46 UTC by revanthakula

2021-06-24 13:44 UTC, narayanagunturi commented on CompareTriplets.cs
> +    }
Please follow proper indentation

2021-06-24 13:45 UTC, narayanagunturi commented on SimpleArraySum.cs
> +    {   int i,sum;
variable "i" can be declared in the for loop itself

2021-06-24 13:46 UTC, narayanagunturi commented on CompareTriplets.cs
> +    {int j;
variable "j" can be declared in the for loop itself

2021-06-24 13:50 UTC, narayanagunturi commented on SimpleArraySum.cs
> +    {   int i,sum;
You can declare this as var sum = 0. Using var keyword in c# is best practice instead of strongly typed data types

2021-06-25 14:07 UTC, revanthakula commented on CompareTriplets.cs
> +    }
Done @narayanagunturi

2021-06-25 14:10 UTC, revanthakula commented on SimpleArraySum.cs
> +    {   int i,sum;
@narayanagunturi 
1.I have changed the "i" declaration.
 2.Usage of var for Variables which are to be returned is showing error.

2021-06-25 14:11 UTC, revanthakula commented on CompareTriplets.cs
> +    {int j;
Done @narayanagunturi .

2021-06-29 06:08 UTC, narayanagunturi requested changes

2021-06-29 06:08 UTC, narayanagunturi commented on CompareTriplets.cs
> +        List<int> c= new List<int> (2);
use var here instead of List<int>

2021-06-29 06:08 UTC, narayanagunturi commented on SimpleArraySum.cs
> +        int sum=0;
use var here

2021-06-29 06:44 UTC, revanthakula commented on SimpleArraySum.cs
> +        int sum=0;
@narayanagunturi done murthy.

2021-06-29 08:05 UTC, revanthakula commented on CompareTriplets.cs
> +        List<int> c= new List<int> (2);
@narayanagunturi done murthy used var instead of list.

2021-06-30 05:07 UTC, narayanagunturi approved these changes

2021-06-30 06:09 UTC, merged